FROM node as builder

RUN mkdir -p /app/frontend
WORKDIR /app/frontend

COPY /frontend/package.json /app/frontend
RUN npm install 

COPY /frontend/. /app/frontend

RUN npm run build

FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY /frontend/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/frontend/build /usr/share/nginx/html