version: "3"

services:
  backend: 
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.dev
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/src:/app/backend/src
    command: nodemon -L src/bin/www.js
    networks: 
      - app-network
    environment:
      - MONGO_URI=mongodb://db:${DB_PORT}/${DB_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - IP_ADDRESS=${IP_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    stdin_open: true
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes: 
      - ./frontend/src:/app/frontend/src
    command: npm run start
    restart: always
    networks:
      - app-network
    environment:
      - REACT_APP_API_IP=http://${IP_ADDRESS}

  db:
    image: mongo
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    entrypoint: sh
    command: -c "mkdir -p /data/screenshots && 
                 mkdir -p /data/files &&
                 mkdir -p /data/backups &&
                 /usr/bin/minio server /data"


  
networks:
  app-network:
    driver: bridge