version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: node dist/bin/www.js
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://db/${DB_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_HOST=minio
      - MINIO_PORT=${MINIO_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports: 
      - "80:80"
    restart: always
    networks:
      - app-network
    environment:
      - REACT_APP_API_IP=http://${IP_ADDRESS}:${BACKEND_PORT}

  db: 
    image: mongo
    restart: always
    networks:
      - app-network

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    entrypoint: sh
    networks: 
      - app-network
    command: -c "mkdir -p /data/screenshots && 
                 mkdir -p /data/files &&
                 mkdir -p /data/backups &&
                 /usr/bin/minio server /data"

networks:
  app-network:
    driver: bridge